### ISSUE TITLE
Consider SHAKE256 over SHA3-512 as recommended by Keccak team and Go team

### ISSUE THREAD

**Issue by x448** [indrora/ponzu#1]
Keccak team and Go team recommend using SHAKE256 instead of SHA3-512.  It's faster than SHA3-512, has 256-bit security, and supports different digest sizes.

SHAKE256 provides 256-bit security when digest is at least 512-bit.  SHAKE256 can also produce 256-bit digest if 128-bit security is acceptable.

> The SHAKE functions are recommended for most new uses. They can produce output of arbitrary length. SHAKE256, with an output length of at least 64 bytes, provides 256-bit security against all attacks. The Keccak team recommends it for most applications upgrading from SHA2-512. (NIST chose a much stronger, but much slower, sponge instance for SHA3-512.)

Source: https://pkg.go.dev/golang.org/x/crypto/sha3

**Comment by indrora** [comment]
SHAKE256, while technically better against preimage attacks and similar, is simultaneously not suggested, but provides no advantages in scope.

The goal is data integrity on the wire and in storage, not modification by a malicious actor.
 
as per [NIST](https://csrc.nist.gov/Projects/Hash-Functions/NIST-Policy-on-Hash-Functions),

> The SHA-3 Extendable-Output Functions (XOFs), SHAKE128 and SHAKE256, can be specialized to hash functions, subject to additional security considerations. Guideline for using the XOFs will be provided in the future.

As described in the final version of [FIPS 202](https://csrc.nist.gov/publications/detail/fips/202/final), section 7:

> SHA3-224, SHA3-256, SHA3-384, and SHA3-512 are approved cryptographic hash functions. [...] SHAKE128 and SHAKE256 are approved XOFs, whose approved uses will be specified in
NIST Special Publications. Although some of those uses may overlap with the uses of approved
hash functions, the XOFs are not approved as hash functions, due to the property that is
discussed in Sec. A.2.

(sec. A.2 here referring to length extension considerations, etc, which NIST/DoD currently relegates to "we don't know how to make these quite as safe as we'd like them, please wait until we have better knowledge")

SHA3-512 will remain the hashing algorithm until such time as guidance on XOFs is made clear for this purpose.

**Comment by x448** [comment]
The sec. A.2. length extension concerns you cited seems to be about digest length extension on XOFs (which is different from message length extension attacks on old Merkle–Damgård hashes).

You can replace SHA3-512 with a faster hash or XOF and only allow 512-bit digests to avoid sec. A.2 concerns about digest length extension from XOFs.

BAD:     allow 256-bit and 512-bit digest sizes from SHAKE256
GOOD:  allow only 256-bit digest from SHAKE256 (128-bit security, faster than SHA3-512)
GOOD:  allow only 512-bit digest from SHAKE256 (256-bit security, faster than SHA3-512)
GOOD:  allow only 512-bit digest from BLAKE2b (256-bit security, faster than SHA3-512)
etc...

I wish you the best and hope your decision to choose SHA3-512 over faster alternatives like BLAKE2, BLAKE3, KangarooTwelve, MarsupilamiFourteen, SHAKE256, etc. isn't based on misunderstandings.

Only reason I opened this issue is because SHA3-512 is very slow and speed matters in a tar alternative like ponzu.

**Comment by indrora** [comment]
Thank you for the clarification on intent. 

You're correct. I chose SHA3-512 as a reasonable medium between "Accepted by standards organizations" and "reasonably novel". 

Contenders in the original set were

* WHIRLPOOL (older ISO acceptable, well described, but with little attention)
* BLAKE2b-512/BLAKE3-512 (reasonably fast, but potentially too novel for some conservative environments)
* MD6 (dq from removal from SHA3 competition)
* SWIFFT (Early NIST elimination)
* RadioGatún (No advantage over Keccak, functionally a proto-Keccak)

Looking at the list of users of Blake2b again, however, I feel that it (or BLAKE2b) might be a good alternative in terms of straight up speed and reliability.
